services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana

  otel-collector:
    build:
      context: ./otel-collector
      dockerfile: Dockerfile
    container_name: north-otel-collector
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
    volumes:
      - ./otel-collector:/etc/otel-collector
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:25.3
    container_name: north-clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"   # HTTP 接口
      - "9000:9000"   # 原生接口
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server

volumes:
  clickhouse_data:
  clickhouse_logs:
