version: '3.8'
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"

networks:
  default:
    name: north-demo
    driver: bridge

services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    logging: *logging

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.123.0
    container_name: otel-collector
    ports:
      - "4317"   # OTLP gRPC receiver
      - "4318"   # OTLP HTTP receiver
    volumes:
      - .config/demo/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      clickhouse:
        condition: service_healthy
    logging: *logging

  clickhouse:
    image: clickhouse/clickhouse-server:25.3
    container_name: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"   # HTTP 接口
      - "9000:9000"   # 原生接口
    environment:
      - CLICKHOUSE_USER=north
      - CLICKHOUSE_PASSWORD=north
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging: *logging

  # Core Demo Services
  ad:
    image: ghcr.io/open-telemetry/demo:latest-ad
    container_name: ad
    restart: unless-stopped
    ports:
      - "9555"
    environment:
      - AD_PORT=9555
      - FLAGD_HOST=flagd
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_SERVICE_NAME=ad
    depends_on:
      otel-collector:
        condition: service_started
    logging: *logging

  cart:
    image: ghcr.io/open-telemetry/demo:latest-cart
    container_name: cart
    restart: unless-stopped
    ports:
      - "7070"
    environment:
      - CART_PORT=7070
      - FLAGD_HOST=flagd
      - VALKEY_ADDR=valkey-cart:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_SERVICE_NAME=cart
      - ASPNETCORE_URLS=http://*:7070
    depends_on:
      valkey-cart:
        condition: service_started
      otel-collector:
        condition: service_started
    logging: *logging

  checkout:
    image: ghcr.io/open-telemetry/demo:latest-checkout
    container_name: checkout
    restart: unless-stopped
    ports:
      - "5050"
    environment:
      - CHECKOUT_PORT=5050
      - CART_ADDR=cart:7070
      - CURRENCY_ADDR=currency:7001
      - EMAIL_ADDR=http://email:6060
      - FLAGD_HOST=flagd
      - PAYMENT_ADDR=payment:50051
      - PRODUCT_CATALOG_ADDR=product-catalog:3550
      - SHIPPING_ADDR=shipping:50050
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_SERVICE_NAME=checkout
    depends_on:
      cart:
        condition: service_started
      currency:
        condition: service_started
      email:
        condition: service_started
      payment:
        condition: service_started
      product-catalog:
        condition: service_started
      shipping:
        condition: service_started
      otel-collector:
        condition: service_started
    logging: *logging

  currency:
    image: ghcr.io/open-telemetry/demo:latest-currency
    container_name: currency
    restart: unless-stopped
    ports:
      - "7001"
    environment:
      - CURRENCY_PORT=7001
      - VERSION=2.0.2
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2,service.name=currency
    depends_on:
      otel-collector:
        condition: service_started
    logging: *logging

  email:
    image: ghcr.io/open-telemetry/demo:latest-email
    container_name: email
    restart: unless-stopped
    ports:
      - "6060"
    environment:
      - APP_ENV=production
      - EMAIL_PORT=6060
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4318/v1/traces
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_SERVICE_NAME=email
    depends_on:
      otel-collector:
        condition: service_started
    logging: *logging

  frontend:
    image: ghcr.io/open-telemetry/demo:latest-frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8080"
    environment:
      - PORT=8080
      - FRONTEND_ADDR=frontend:8080
      - AD_ADDR=ad:9555
      - CART_ADDR=cart:7070
      - CHECKOUT_ADDR=checkout:5050
      - CURRENCY_ADDR=currency:7001
      - PRODUCT_CATALOG_ADDR=product-catalog:3550
      - RECOMMENDATION_ADDR=recommendation:9001
      - SHIPPING_ADDR=shipping:50050
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_SERVICE_NAME=frontend
      - PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:8080/otlp-http/v1/traces
      - WEB_OTEL_SERVICE_NAME=frontend-web
      - OTEL_COLLECTOR_HOST=otel-collector
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
    depends_on:
      ad:
        condition: service_started
      cart:
        condition: service_started
      checkout:
        condition: service_started
      currency:
        condition: service_started
      product-catalog:
        condition: service_started
      quote:
        condition: service_started
      recommendation:
        condition: service_started
      shipping:
        condition: service_started
      otel-collector:
        condition: service_started
      image-provider:
        condition: service_started
    logging: *logging

  frontend-proxy:
    image: ghcr.io/open-telemetry/demo:latest-frontend-proxy
    container_name: frontend-proxy
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "10000:10000"
    environment:
      - FRONTEND_PORT=8080
      - FRONTEND_HOST=frontend
      - LOCUST_WEB_HOST=load-generator
      - LOCUST_WEB_PORT=8089
      - GRAFANA_PORT=3000
      - GRAFANA_HOST=grafana
      - OTEL_COLLECTOR_HOST=otel-collector
      - IMAGE_PROVIDER_HOST=image-provider
      - IMAGE_PROVIDER_PORT=8081
      - OTEL_COLLECTOR_PORT_GRPC=4317
      - OTEL_COLLECTOR_PORT_HTTP=4318
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_SERVICE_NAME=frontend-proxy
      - ENVOY_PORT=8080
      - FLAGD_HOST=flagd
      - FLAGD_PORT=8013
      - FLAGD_UI_HOST=flagd-ui
      - FLAGD_UI_PORT=4000
      - JAEGER_PORT=16686
      - JAEGER_HOST=jaeger
    depends_on:
      frontend:
        condition: service_started
      load-generator:
        condition: service_started
      grafana:
        condition: service_started
    dns_search: ""

  image-provider:
    image: ghcr.io/open-telemetry/demo:latest-image-provider
    container_name: image-provider
    restart: unless-stopped
    ports:
      - "8081"
    environment:
      - IMAGE_PROVIDER_PORT=8081
      - OTEL_COLLECTOR_HOST=otel-collector
      - OTEL_COLLECTOR_PORT_GRPC=4317
      - OTEL_SERVICE_NAME=image-provider
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
    depends_on:
      otel-collector:
        condition: service_started
    logging: *logging

  load-generator:
    image: ghcr.io/open-telemetry/demo:latest-load-generator
    container_name: load-generator
    restart: unless-stopped
    ports:
      - "8089"
    environment:
      - LOCUST_WEB_PORT=8089
      - LOCUST_USERS=5
      - LOCUST_HOST=http://frontend-proxy:8080
      - LOCUST_HEADLESS=false
      - LOCUST_AUTOSTART=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_SERVICE_NAME=load-generator
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - LOCUST_WEB_HOST=0.0.0.0
      - FLAGD_HOST=flagd
      - FLAGD_OFREP_PORT=8016
    depends_on:
      frontend:
        condition: service_started
      flagd:
        condition: service_started
    logging: *logging

  payment:
    image: ghcr.io/open-telemetry/demo:latest-payment
    container_name: payment
    restart: unless-stopped
    ports:
      - "50051"
    environment:
      - FLAGD_HOST=flagd
      - PAYMENT_PORT=50051
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_SERVICE_NAME=payment
    depends_on:
      otel-collector:
        condition: service_started
    logging: *logging

  product-catalog:
    image: ghcr.io/open-telemetry/demo:latest-product-catalog
    container_name: product-catalog
    restart: unless-stopped
    ports:
      - "3550"
    environment:
      - FLAGD_HOST=flagd
      - PRODUCT_CATALOG_PORT=3550
      - PRODUCT_CATALOG_RELOAD_INTERVAL=10
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_SERVICE_NAME=product-catalog
    volumes:
      - .config/demo/products:/usr/src/app/products
    depends_on:
      otel-collector:
        condition: service_started
    logging: *logging

  quote:
    image: ghcr.io/open-telemetry/demo:latest-quote
    container_name: quote
    restart: unless-stopped
    ports:
      - "8090"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - QUOTE_PORT=8090
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_SERVICE_NAME=quote
      - OTEL_PHP_INTERNAL_METRICS_ENABLED=true
    depends_on:
      otel-collector:
        condition: service_started
    logging: *logging

  recommendation:
    image: ghcr.io/open-telemetry/demo:latest-recommendation
    container_name: recommendation
    restart: unless-stopped
    ports:
      - "9001"
    environment:
      - FLAGD_HOST=flagd
      - RECOMMENDATION_PORT=9001
      - PRODUCT_CATALOG_ADDR=product-catalog:3550
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_SERVICE_NAME=recommendation
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
    depends_on:
      product-catalog:
        condition: service_started
      otel-collector:
        condition: service_started
    logging: *logging

  shipping:
    image: ghcr.io/open-telemetry/demo:latest-shipping
    container_name: shipping
    restart: unless-stopped
    ports:
      - "50050"
    environment:
      - SHIPPING_PORT=50050
      - QUOTE_ADDR=http://quote:8090
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_SERVICE_NAME=shipping
    depends_on:
      otel-collector:
        condition: service_started
    logging: *logging

  # Dependent Services
  flagd:
    image: ghcr.io/open-feature/flagd:v0.12.1
    container_name: flagd
    environment:
      - FLAGD_OTEL_COLLECTOR_URI=otel-collector:4317
      - FLAGD_METRICS_EXPORTER=otel
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=north-demo,service.version=2.0.2
      - OTEL_SERVICE_NAME=flagd
    command: [
      "start",
      "--uri",
      "file:./etc/flagd/demo.flagd.json"
    ]
    ports:
      - "8013"
      - "8016"
    volumes:
      - .config/demo/flagd:/etc/flagd
    logging: *logging

  valkey-cart:
    image: valkey/valkey:8.1-alpine
    container_name: valkey-cart
    user: valkey
    restart: unless-stopped
    ports:
      - "6379"
    logging: *logging